"""streaks

Revision ID: 6c902267104e
Revises: c4bd2582494f
Create Date: 2024-08-22 12:16:02.185407

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c902267104e"
down_revision: Union[str, None] = "c4bd2582494f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streaks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_read_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("streak_days", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_streaks_id"), "streaks", ["id"], unique=False)
    op.add_column("articles", sa.Column("date_first_accessed", sa.DateTime(), nullable=True))
    op.add_column("articles", sa.Column("date_last_accessed", sa.DateTime(), nullable=True))
    op.drop_column("articles", "read")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("read", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False)
    )
    op.drop_column("articles", "date_last_accessed")
    op.drop_column("articles", "date_first_accessed")
    op.drop_index(op.f("ix_streaks_id"), table_name="streaks")
    op.drop_table("streaks")
    # ### end Alembic commands ###
