"""Initial migration

Revision ID: b9a5ae5a224a
Revises:
Create Date: 2024-08-13 11:41:53.590140

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9a5ae5a224a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("articles", "url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("articles", "read", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("articles", "user_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("articles", "user_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("articles", "read", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("articles", "url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
