"""update_articles_last_access_date_read

Revision ID: c4bd2582494f
Revises: b9a5ae5a224a
Create Date: 2024-08-15 13:26:36.986051

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4bd2582494f"
down_revision: Union[str, None] = "b9a5ae5a224a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("date_first_accessed", sa.DateTime(), nullable=True))
    op.add_column("articles", sa.Column("date_last_accessed", sa.DateTime(), nullable=True))
    op.drop_column("articles", "read")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("read", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("articles", "date_last_accessed")
    op.drop_column("articles", "date_first_accessed")
    # ### end Alembic commands ###
