name: Deploy Backend

on:
  push:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - production

jobs:
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.event_name == 'push' && 'dev') || (github.event_name == 'release' && 'production') }}

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          if [ -z "$HOST" ]; then
            echo "Error: HOST is empty or not set"
            exit 1
          fi

          if [ -z "$USER" ]; then
            echo "Error: USER is empty or not set"
            exit 1
          fi

          if [ -z "$PRIVATE_KEY" ]; then
            echo "Error: PRIVATE_KEY is empty or not set"
            exit 1
          fi

          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          echo "Creating directory if it doesn't exist..."
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'mkdir -p ~/fastapi-app'

          echo "Copying files..."
          scp -i private_key -o StrictHostKeyChecking=no -r ./backend/* ${USER}@${HOST}:~/fastapi-app

          echo "Running deployment commands..."
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd ~/fastapi-app &&
            pip install -r requirements.txt &&
            sudo systemctl restart fastapi-app
          '

          echo "Cleaning up..."
          rm private_key

          echo "Deployment completed successfully."
