name: CD - Deploy Backend

on:
  release:
    types: [published]
  repository_dispatch:
    types: [run-cd]
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      AWS_SSH_PRIVATE_KEY:
        required: true
      AWS_HOST:
        required: true
      AWS_USER:
        required: true
      POSTGRES_USER:
        required: true
      POSTGRES_PASSWORD:
        required: true
      POSTGRES_DB:
        required: true
      POSTGRES_HOST:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - production

jobs:
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || github.event.inputs.environment || (github.event_name == 'push' && 'dev') || (github.event_name == 'release' && 'production') }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/economemo-backend:latest

      - name: Deploy to EC2 and Verify FastAPI Server
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.AWS_HOST }}
          USER: ${{ secrets.AWS_USER }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/economemo-backend:latest &&
            docker stop economemo-backend || true &&
            docker rm economemo-backend || true &&
            docker run -d --name economemo-backend \
              -p 8000:8000 \
              -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
              -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
              -e POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
              -e POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/economemo-backend:latest

            echo "Debugging: Printing POSTGRES_HOST from container..."
            docker exec economemo-backend printenv POSTGRES_HOST

            echo "Waiting for FastAPI server to start..."
            sleep 5

            start_time=$(date +%s)
            end_time=$((start_time + 10))

            while [ $(date +%s) -lt $end_time ]; do
              echo "Verifying that FastAPI backend is up and running..."
              if curl -sSf http://localhost:8000/health > /dev/null 2>&1; then
                echo "FastAPI server is up and running!"
                exit 0
              fi
              sleep 1
            done

            echo "Failed to verify server status after 10 seconds"
            docker logs economemo-backend
            exit 1
          '
          rm private_key
