name: Deploy Backend to Dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    # ... [Test job remains unchanged] ...

  deploy-dev:
    name: Deploy to Dev
    needs: test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 # Adjust this to your AWS region

      - name: Retrieve secrets from AWS
        run: |
          echo "AWS_HOST=$(aws ssm get-parameter --name "/dev/AWS_HOST" --with-decryption --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "AWS_USER=$(aws ssm get-parameter --name "/dev/AWS_USER" --with-decryption --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          aws ssm get-parameter --name "/dev/AWS_SSH_PRIVATE_KEY" --with-decryption --query "Parameter.Value" --output text > private_key
          chmod 600 private_key

      - name: Deploy to EC2 Dev
        run: |
          scp -i private_key -o StrictHostKeyChecking=no -r ./backend/* ${AWS_USER}@${AWS_HOST}:~/fastapi-app
          ssh -i private_key -o StrictHostKeyChecking=no ${AWS_USER}@${AWS_HOST} '
            cd ~/fastapi-app &&
            pip install -r requirements.txt &&
            sudo systemctl restart fastapi-app
          '
