name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r backend/requirements.txt

    - name: Setup Database
      run: |
        sudo apt-get install -y postgresql-client
        psql -h localhost -U testuser -c "DROP DATABASE IF EXISTS testdb;"
        psql -h localhost -U testuser -c "CREATE DATABASE testdb;"
      env:
        PGPASSWORD: testpassword

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -v
      env:
        DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
