name: CI/CD - Build, Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml

  wait-for-ci:
    needs: run-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI Completed
        run: echo "CI workflow completed successfully"

  run-cd:
    needs: wait-for-ci
    uses: ./.github/workflows/cd.yml
    with:
      environment: "dev"
