name: CI/CD - Build, Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml

  wait-for-ci:
    needs: run-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI Completed
        run: echo "CI workflow completed successfully"

  run-cd:
    needs: wait-for-ci
    uses: ./.github/workflows/cd.yml
    with:
      environment: "dev"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
      AWS_HOST: ${{ secrets.AWS_HOST }}
      AWS_USER: ${{ secrets.AWS_USER }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      SSL_KEYFILE: ${{ secrets.SSL_KEYFILE }}
      SSL_CERTFILE: ${{ secrets.SSL_CERTFILE }}
      PORT: ${{ secrets.PORT }}
      DOMAIN: ${{ secrets.DOMAIN }}
      CHROME_EXTENSION_IDS: ${{ secrets.CHROME_EXTENSION_IDS }}
