name: CI/CD - Build, Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger CI Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: run-ci

  wait-for-ci:
    needs: trigger-ci
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI to complete
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: "CI Success"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  trigger-cd:
    needs: wait-for-ci
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CD Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: run-cd
